 const AssociatesJSON = [
    {
        associateName: "Rajiv Madassery (BLR)",
        w3id: "rajiv@ibm.com",
        managerName: "",
        role: "Manager",
        location: "Bangalore",
      },
      {
        associateName: "Ashima Singhal",
        w3id: "ashima@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Shreyashi Bhowmick",
        w3id: "shreyashi@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Roushan Kumar",
        w3id: "roushan@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Samarpita Pattnaik",
        w3id: "samarpita@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Mounika Grandhi",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Madhavi Pilaka",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Abdul Shad",
        w3id: "madhavi@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Pallavi Sinha",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Nalla Swathi Rekha",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Jyothi Priya Kalluri",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Hariprasad AS",
        w3id: "hari@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Team lead",
        location: "Bangalore",
      },
      {
        associateName: "Sheetal Shreya",
        w3id: "sheetal@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Mounika Grandhi",
        w3id: "mouni@ibm.com",
        managerName: "Rajiv Madassery",
        role: "Associate",
        location: "Bangalore",
      },
      {
        associateName: "Manoj Nair (PUN)",
        w3id: "mouni@ibm.com",
        managerName: "",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Tarun Singh",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Princy Katlana",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Jitendra Buge",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Nitin Darade",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Manish Jadhav",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Rahul Kajve",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Abhishek Khandagale",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Varada Kolhe",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Pradeep Pawar",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Suhas Phansalkar",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Jophy Joe",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Anuradha Narendra",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Nair",
        role: "Associate",
        location: "Pune",
      },
      {
        associateName: "Manoj Kumar Goyal (AHM)",
        w3id: "mouni@ibm.com",
        managerName: "",
        role: "Associate",
        location: "Ahmedabad",
      },
      {
        associateName: "Shantanu Singh",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Kumar Goyal",
        role: "Associate",
        location: "Ahmedabad",
      },
      {
        associateName: "Sushmita Gour",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Kumar Goyal",
        role: "Associate",
        location: "Ahmedabad",
      },
      {
        associateName: "Mitrajsinh Jadeja",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Kumar Goyal",
        role: "Associate",
        location: "Ahmedabad",
      },
      {
        associateName: "Dhruti Badiani",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Kumar Goyal",
        role: "Associate",
        location: "Ahmedabad",
      },
      {
        associateName: "Urja Rajpara",
        w3id: "mouni@ibm.com",
        managerName: "Manoj Kumar Goyal",
        role: "Associate",
        location: "Ahmedabad",
      },
];

export default AssociatesJSON;